### ISSUE TITLE
Using Filters results in 500 Server Error

### ISSUE THREAD

**Issue by cmhnk** [matfish2/craft-activity-log#17]
** Versions **
Craft: 4.12.7
Activity Logs: 1.7.2

**Describe the bug**
Filters are not working; the spinner icon appears and continues spinning indefinitely. 
A 500 Server Error is logged in Network Requests. 

**Screenshots**
<img width="1215" alt="image" src="https://github.com/user-attachments/assets/9edfdc81-a579-4576-a58a-580b6189e9f6" />

Request:
<img width="1357" alt="image" src="https://github.com/user-attachments/assets/193ff3c9-76cd-4dc9-99c9-121869790a03" />

Response:
<img width="1446" alt="image" src="https://github.com/user-attachments/assets/85f41180-bcac-4070-a26d-6f343f0eaa31" />

**Comment by matfish2** [comment]
Thanks for reporting @cmhnk.  I'll look into it tomorrow 
Can you please share the actual error from the error logs in Craft?
Under `storage/log/web-{date}.log`

**Comment by cmhnk** [comment]
Thanks for the quick response @matfish2, really appreciate it! 

Here's the relevant bit from the logs

1) Using the "Action" filter dropdown
```
2024-12-21 08:47:50 [web.INFO] [yii\db\Connection::open] Opening DB connection: mysql:host=127.0.0.1;dbname=kindred;port=3306 {"memory":771400} 
2024-12-21 08:47:50 [web.INFO] [yii\web\Session::open] Session started {"memory":2018336} 
2024-12-21 08:47:50 [web.INFO] [mmikkel\cpfieldinspect\CpFieldInspect::init] CP Field Inspect plugin loaded {"memory":2341336} 
2024-12-21 08:47:50 [web.ERROR] [TypeError] TypeError: json_decode(): Argument #1 ($json) must be of type string, array given in /Users/cjojic/code/kindred/kindred-motorworks-cms/vendor/matfish/craft-activity-log/src/services/VueTablesActivityLogRetriever.php:34
Stack trace:
#0 /Users/cjojic/code/kindred/kindred-motorworks-cms/vendor/matfish/craft-activity-log/src/services/VueTablesActivityLogRetriever.php(34): json_decode(Array, true)
#1 /Users/cjojic/code/kindred/kindred-motorworks-cms/vendor/matfish/craft-activity-log/src/controllers/ActivityLogController.php(177): matfish\ActivityLog\services\VueTablesActivityLogRetriever->retrieve()
#2 [internal function]: matfish\ActivityLog\controllers\ActivityLogController->actionData()
#3 /Users/cjojic/code/kindred/kindred-motorworks-cms/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#4 /Users/cjojic/code/kindred/kindred-motorworks-cms/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#5 /Users/cjojic/code/kindred/kindred-motorworks-cms/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('data', Array)
#6 /Users/cjojic/code/kindred/kindred-motorworks-cms/vendor/craftcms/cms/src/web/Application.php(341): yii\base\Module->runAction('activity-logs/a...', Array)
#7 /Users/cjojic/code/kindred/kindred-motorworks-cms/vendor/craftcms/cms/src/web/Application.php(640): craft\web\Application->runAction('activity-logs/a...', Array)
#8 /Users/cjojic/code/kindred/kindred-motorworks-cms/vendor/craftcms/cms/src/web/Application.php(303): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#9 /Users/cjojic/code/kindred/kindred-motorworks-cms/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#10 /Users/cjojic/code/kindred/kindred-motorworks-cms/web/index.php(26): yii\base\Application->run()
#11 /Users/cjojic/.composer/vendor/laravel/valet/server.php(110): require('/Users/cjojic/c...')
#12 {main} {"memory":2747088,"exception":"[object] (TypeError(code: 0): json_decode(): Argument #1 ($json) must be of type string, array given at /Users/cjojic/code/kindred/kindred-motorworks-cms/vendor/matfish/craft-activity-log/src/services/VueTablesActivityLogRetriever.php:34)"} 
2024-12-21 08:47:50 [web.INFO] [application] Request context:
$_GET = [
    'action' => 'activity-logs/activity-log/data'
    'limit' => '10'
    'ascending' => '0'
    'page' => '1'
    'byColumn' => '1'
    'orderBy' => 'createdAt'
    'createdAt' => ''
    'actionSegments' => [
        'type' => 'equal'
        'q' => '[\"commerce\",\"products\",\"save-product\"]'
    ]
    'payload' => ''
]
```

2) Typing in a value in the User filter:
```
2024-12-21 08:51:04 [web.ERROR] [TypeError] TypeError: json_decode(): Argument #1 ($json) must be of type string, array given in /Users/cjojic/code/kindred/kindred-motorworks-cms/vendor/matfish/craft-activity-log/src/services/VueTablesActivityLogRetriever.php:27
Stack trace:
#0 /Users/cjojic/code/kindred/kindred-motorworks-cms/vendor/matfish/craft-activity-log/src/services/VueTablesActivityLogRetriever.php(27): json_decode(Array, true)
#1 /Users/cjojic/code/kindred/kindred-motorworks-cms/vendor/matfish/craft-activity-log/src/controllers/ActivityLogController.php(177): matfish\ActivityLog\services\VueTablesActivityLogRetriever->retrieve()
#2 [internal function]: matfish\ActivityLog\controllers\ActivityLogController->actionData()
#3 /Users/cjojic/code/kindred/kindred-motorworks-cms/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#4 /Users/cjojic/code/kindred/kindred-motorworks-cms/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#5 /Users/cjojic/code/kindred/kindred-motorworks-cms/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('data', Array)
#6 /Users/cjojic/code/kindred/kindred-motorworks-cms/vendor/craftcms/cms/src/web/Application.php(341): yii\base\Module->runAction('activity-logs/a...', Array)
#7 /Users/cjojic/code/kindred/kindred-motorworks-cms/vendor/craftcms/cms/src/web/Application.php(640): craft\web\Application->runAction('activity-logs/a...', Array)
#8 /Users/cjojic/code/kindred/kindred-motorworks-cms/vendor/craftcms/cms/src/web/Application.php(303): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#9 /Users/cjojic/code/kindred/kindred-motorworks-cms/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#10 /Users/cjojic/code/kindred/kindred-motorworks-cms/web/index.php(26): yii\base\Application->run()
#11 /Users/cjojic/.composer/vendor/laravel/valet/server.php(110): require('/Users/cjojic/c...')
#12 {main} {"memory":2745856,"exception":"[object] (TypeError(code: 0): json_decode(): Argument #1 ($json) must be of type string, array given at /Users/cjojic/code/kindred/kindred-motorworks-cms/vendor/matfish/craft-activity-log/src/services/VueTablesActivityLogRetriever.php:27)"} 
2024-12-21 08:51:04 [web.INFO] [application] Request context:
$_GET = [
    'action' => 'activity-logs/activity-log/data'
    'query' => [
        'userId' => 'Corinne'
    ]
    'limit' => '10'
    'ascending' => '0'
    'page' => '1'
    'byColumn' => '1'
    'orderBy' => 'createdAt'
    'createdAt' => ''
    'actionSegments' => ''
    'payload' => ''
]
```

**Comment by matfish2** [comment]
@cmhnk please can you try version 1.7.3? 
I believe it should be resolved now (unable to reproduce on my end so not entirely sure)
